name: Release Trigger

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (without v prefix)'
        required: true
        type: string

permissions:
  contents: write

jobs:
  create-tag-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Update version in Cargo.toml
        run: |
          sed -i "s/^version = \".*\"/version = \"${{ github.event.inputs.version }}\"/" Cargo.toml
          git add Cargo.toml

      - name: Commit and tag
        run: |
          git commit -m "chore: bump version to ${{ github.event.inputs.version }}"
          git tag -a "v${{ github.event.inputs.version }}" -m "Release v${{ github.event.inputs.version }}"

      - name: Push changes
        run: |
          git push origin HEAD:master
          git push origin "v${{ github.event.inputs.version }}"

      - name: Wait for pipeline to start
        run: |
          echo "Tag v${{ github.event.inputs.version }} has been pushed."
          echo "The main pipeline will now build and create a release automatically."
          echo "You can monitor the progress in the Actions tab."
          echo "Waiting 10 seconds to allow the pipeline to start..."
          sleep 10